package com.banlinhkien.auth;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Spike Test to verify that Spring Security's BCryptPasswordEncoder natively and accurately
 * verifies real password hashes generated by PHP Laravel 11 ($2y$ with varying cost factors).
 */
public class BcryptSpikeTest {

    private final BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

    @ParameterizedTest(name = "Verify user {0} (cost {2}) with raw password ''{1}''")
    @CsvSource({
        "test2, 12345678, 10, $2y$10$5Io5RhawO.C/dSiWXOaGlOzlRC8UBX6bQ6WtSbC/gpyWXdAL8/0sa",
        "nguyenvana, password, 12, $2y$12$yqBq/hbT8x8XpcgYPNy3YuMf7eQ7gbxALfELEe4H3Nn1hea0iK22q",
        "tranthib, password, 10, $2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        "admin123_vector, admin123, 10, $2y$10$9Z81mLGd7/AncNjsx0SDaeniWyKek8Rj/BTFgfdDiY9CibFWjlp22",
        "password2026_vector, password@2026, 12, $2y$12$HZUKp.wQK32SjsGgoI6y6eOCtT6/Rq33YRwt8y.BQBIBPB0B0R4Km",
        "customer99_vector, customer#99, 11, $2y$11$4H4hfwrxbTizNsZZqtKY2uT/DDnYdWyNlxnaHlqCf087sWuxHx9aa"
    })
    @DisplayName("Should successfully match real Laravel $2y$ BCrypt hashes across multiple cost factors")
    void shouldMatchLaravelBcryptHashes(String username, String rawPassword, int cost, String storedHash) {
        // Assert stored hash format
        assertThat(storedHash).startsWith("$2y$" + cost + "$");

        // Verify password against BCryptPasswordEncoder
        boolean matches = encoder.matches(rawPassword, storedHash);
        assertThat(matches)
                .withFailMessage("Failed to match password '%s' against hash '%s' for user '%s'", rawPassword, storedHash, username)
                .isTrue();
    }

    @Test
    @DisplayName("Should reject incorrect password when matched against real Laravel hash")
    void shouldRejectWrongPassword() {
        String realHash = "$2y$12$yqBq/hbT8x8XpcgYPNy3YuMf7eQ7gbxALfELEe4H3Nn1hea0iK22q";
        assertThat(encoder.matches("wrong_password_123", realHash)).isFalse();
    }

    @Test
    @DisplayName("Should verify that BCrypt dynamically reads cost factor from the hash string without hardcoding")
    void shouldDynamicallyDetectCostFactor() {
        String cost10Hash = "$2y$10$5Io5RhawO.C/dSiWXOaGlOzlRC8UBX6bQ6WtSbC/gpyWXdAL8/0sa";
        String cost12Hash = "$2y$12$yqBq/hbT8x8XpcgYPNy3YuMf7eQ7gbxALfELEe4H3Nn1hea0iK22q";

        assertThat(encoder.matches("12345678", cost10Hash)).isTrue();
        assertThat(encoder.matches("password", cost12Hash)).isTrue();
    }
}
